### ISSUE TITLE
error installing zonation on linux

### ISSUE THREAD

**Issue by cbaldeck** [cbig/zonation-core#15] opened 2017-03-20 15:54 UTC
When I try to use the "make" command, I get the following error:

/usr/local/lib/zonation/zonation-core-master/zig4lib/io_matrix_load.cpp:10:51: fatal error: boost/spirit/home/phoenix/container.hpp: No such file or directory
compilation terminated.

Everything worked great until that point.  I am using Ubuntu 16.04.

Any help would be much appreciated!

**Comment by jlehtoma** [comment] 2017-03-20 16:05
You probably have too recent version of `boost` installed. If memory serves, versions <= 1.55 and >= 1.48 is required. Ubuntu 14.04 still works, 16.06 needs some additional work. @PKullberg : did you manage to do this on 16.06?

**Comment by PKullberg** [comment] 2017-03-20 16:18
Yes, I compiled Zonation on Ubuntu 16.04 against boost version 1.55 (www.boost.org/users/history/version_1_55_0.html) and it works fine.

**Comment by cbaldeck** [comment] 2017-03-20 17:19
Yes the version installed from apt-get install libboost-all-dev is 1.58.0.1.  Do I need to install version 1.55 instead?

**Comment by jlehtoma** [comment] 2017-03-21 11:33
@cbaldeck : yes, it that's available on Ubuntu 16.06. I think @PKullberg compiled 1.55 himself from source code (?).

**Comment by PKullberg** [comment] 2017-03-21 17:58
Yep, I compiled Boost 1.55 from source. If you have troubles getting it working, I can take a look if I have some documentation on how I did it later this week.

**Comment by cbaldeck** [comment] 2017-03-21 18:30
I replaced libboost-all-dev with libboost 1.55* and re-ran everything.  I got a different error message this time:

fatal error: boost/function.hpp: No such file or directory

**Comment by cbaldeck** [comment] 2017-03-31 18:15
I believe I got zonation installed correctly by uninstalling the libboost-all-dev and installing the libboost 1.55.  I continued with the instructions and everything seemed to work great but then the last part, the tutorial run, threw errors

zrunner -l tutorial_runs.yaml
ERROR: Input YAML file {0} does not exist

I do not know if this means that zrunner did not install correctly or if there is something else going on.  

Thank you for your help with this!

**Comment by jlehtoma** [comment] 2017-04-01 11:53
`zrunner` was probably installed OK, but it can't find a configuration file defining which runs to execute as there was a small error in the call. Once you've cloned/downloaded the tutorial, try the following:

```
cd zonation-tutorial
zrunner -l tests/tutorial_runs.yaml
```

**Comment by cbaldeck** [comment] 2017-04-01 12:25
I removed the zonation-tutorial folder and ran

`git clone https://github.com/cbig/zonation-tutorial.git`

again to reinstall the tutorial then ran 

```
cd zonation-tutorial
zrunner -l tests/tutorial_runs.yaml
```

and got the same message:
ERROR: Input YAML file {0} does not exist

Did I install the correct tutorial?

**Comment by jlehtoma** [comment] 2017-04-01 12:57
Sorry, my bad again... How about:

```
cd zonation-tutorial
zrunner -l basic/tests/tutorial_runs.yaml
```

If that still doesn't work, see [the basic tutorial](https://github.com/cbig/zonation-tutorial) directory structure to locate `tutorial_runs.yaml`

**Comment by cbaldeck** [comment] 2017-04-01 13:02
I don't see tutorial_runs.yaml anywhere... If I search the directory I
don't get a result.  The only .yaml file I see in /basic/tests is
ztests_basic.yaml and if I try this with zrunner it says "ERROR: None of
the input files exist"

**Comment by cbaldeck** [comment] 2017-04-01 13:08
Ah I tried another thing:  Following the instructions on https://github.com/cbig/zonation-tutorial/tree/master/basic/tests I navigated to the /zonation-tutorial/basic/tests folder and tried 

`zrunner -l ztests_basic.yaml`

Then I got: 
Traceback (most recent call last):
  File "/usr/local/bin/zrunner", line 9, in <module>
    load_entry_point('ztools==0.2.dev20170331', 'console_scripts', 'zrunner')()
  File "/usr/local/lib/python2.7/dist-packages/ztools/runner.py", line 237, in main
    output['z_info'] = get_zonation_info(args.executable)
  File "/usr/local/lib/python2.7/dist-packages/ztools/utilities.py", line 68, in get_zonation_info
    version, errs = version.communicate()[0]
ValueError: too many values to unpack

**Comment by jlehtoma** [comment] 2017-04-01 13:32
`zrunner` seems to have multiple issues with dependencies and some bugs, which I don't have time to fix now. I did update the `zonation-tutorial` repo, though. If you get the latest version, you should see bash shell script versions of the bat-files (e.g. `do_01_core_area_zonation.sh`). You can execute the runs individually by doing the following:

```
cd zonation-tutorial/basic
sh do_01_core_area_zonation.sh
sh do_02_additive_benefit_function.sh
etc.
```

**Comment by cbaldeck** [comment] 2017-04-01 14:06
That is OK.  I do not care about running things with the zrunner so much, I just want to confirm that zonation has been properly installed and is working on my computer.   To try your shell script, I first had to create the file "01_core_area_zonation" in the /basic_output folder, otherwise it throws errors saying the output path does not exist.  After making this folder, I tried 
```
cd zonation-tutorial/basic
sh do_01_core_area_zonation.sh
```
and it says "can't open file basic_output/01_core_area_zonation/01_core_area_zonation.txt"

Ultimately though, I would like to run things using zonator in R.  However, I can't find instructions on how to do this.  In R, if I try 
```
vignette("zonator-project")
vignette("zonator-results")
```
it says "Warning message: vignette ‘zonator-project’ not found" or "Warning message: vignette ‘zonator-results’ not found" 
Thus I still cannot tell if I have zonation properly installed and working or if I have a problem with the communication between zonator and zonation.

**Comment by jlehtoma** [comment] 2017-04-01 14:31
> That is OK. I do not care about running things with the zrunner so much, I just want to confirm 
> that zonation has been properly installed and is working on my computer. To try your shell 
> script, I first had to create the file "01_core_area_zonation" in the /basic_output folder, otherwise 
> it throws errors saying the output path does not exist. After making this folder, I tried
> ```
> cd zonation-tutorial/basic
> sh do_01_core_area_zonation.sh
> ```
> and it says "can't open file basic_output/01_core_area_zonation/01_core_area_zonation.txt"

I can't reproduce the error. For me, the commands you use here work. Zonation automatically creates the `01_core_area_zonation` directory within `basic_output` so you shouldn't need to do that manually.

> Ultimately though, I would like to run things using zonator in R. 

Currently, you can only set up Zonation runs and read in the results using `zonator`. but you can't actually run Zonation. Enabling this functionality using e.g. `system()` calls shouldn't be too difficult, though. Happy to accept pull requests on `zonator` if you get around doing it.

> However, I can't find instructions > on how to do this. In R, if I try
> ```
> vignette("zonator-project")
> vignette("zonator-results")
> ```
> it says "Warning message: vignette ‘zonator-project’ not found" or "Warning message: vignette 
> ‘zonator-results’ not found"

Thanks for reporting this, I haven't tested it in a while. You need to [explicitly tell `install_github()` to build vignettes](https://stackoverflow.com/questions/33614660/knitr-rmd-vignettes-do-not-appear-with-vignette) when installing `zonator`:

```
devtools::install_github("cbig/zonator", build_vignettes = TRUE)
```

After this, `vignette()` calls should work. I've updated the `zonator` installation instructions.

> Thus I still cannot tell if I have zonation properly installed and working or if I have a problem with > the communication between zonator and zonation.

**Comment by cbaldeck** [comment] 2017-04-01 14:40
Yes this fixed the vignette() calls problem.  I will see how far I can get
with this in R.

As far as not being able to run the shell scripts, this may have to do with
my system... I am going to check with someone this week to see if I can get
it running.

Thank you for all your help on this!

**Comment by cbaldeck** [comment] 2017-04-08 16:46
Got it working with the shell script!  Thank you very much!!

**Comment by jlehtoma** [comment] 2017-04-09 13:19
Great, glad to hear! Closing this issue.

**Closed as completed by jlehtoma** 2017-04-09 13:19 UTC
